//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Artist
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual Date Birthday
	{
		get;
		set;
	}

	public Artist(string name, Date birthdat)
	{
	}

	public virtual void Add(Song song)
	{
		throw new System.NotImplementedException();
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

}

