//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MusicPlayer
{
	public virtual IEnumerable<Song> Song
	{
		get;
		set;
	}

	public virtual IEnumerable<Artist> Artist
	{
		get;
		set;
	}

	public virtual IEnumerable<Playlist> Playlist
	{
		get;
		set;
	}

	public MusicPlayer()
	{
	}

	public virtual void Add(Artist artist)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Add(Song song)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Add(Playlist playlist)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Play(Song song)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Play(Playlist platlist)
	{
		throw new System.NotImplementedException();
	}

	public virtual Song Playing()
	{
		throw new System.NotImplementedException();
	}

	public virtual void StopPlaying()
	{
		throw new System.NotImplementedException();
	}

}

