//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Song
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual int Year
	{
		get;
		set;
	}

	public virtual string PathToFile
	{
		get;
		set;
	}

	public virtual string Lyrics
	{
		get;
		set;
	}

	public Song(object name string, int year, Artist artist, string pathOfFile)
	{
	}

	public virtual string ToSrting()
	{
		throw new System.NotImplementedException();
	}

}

